// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package view

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import (
	// "github.com/michelemendel/dmtmms/constants"

	"github.com/michelemendel/dmtmms/entity"
)

func (vctx *ViewCtx) MemberFormModal(member entity.Member) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templ.WriteWatchModeString(templ_7745c5c3_Buffer, 1)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(member.Name))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.WriteWatchModeString(templ_7745c5c3_Buffer, 2)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}

// templ (vctx *ViewCtx) MemberForm(uuid string) {
// 	if ctx.Value(constants.CTX_IS_XHR_KEY).(bool) {
// 		@vctx.MemberFormPage()
// 	} else {
// 		@vctx.AppRoot("") {
// 			@vctx.MemberFormPage()
// 		}
// 	}
// }

// templ (vctx *ViewCtx) MemberFormPage() {
// 	<div id="memberForm">
// 		<form>
// 			<div class="relative">
// 				<button
// 					class={ ButtonClass }
// 				>
// 					Get bundle
// 				</button>
// 			</div>
// 			<div class="relative">
// 				<details class="dropdown">
// 					<summary class="m-1 btn">open or close</summary>
// 					<ul class="p-2 shadow menu dropdown-content z-[1] bg-base-100 rounded-box w-52">
// 						<li><a>Item 1</a></li>
// 						<li><a>Item 2</a></li>
// 					</ul>
// 				</details>
// 			</div>
// 			<div class="dropdown">
// 				<div tabindex="0" role="button" class="btn m-1">Click</div>
// 				<ul tabindex="0" class="dropdown-content z-[1] menu p-2 shadow bg-base-100 rounded-box w-52">
// 					<li><a>Item 1</a></li>
// 					<li><a>Item 2</a></li>
// 				</ul>
// 			</div>
// 			<button class="btn btn-primary">Button</button>
// 		</form>
// 		<span class="countdown font-mono text-6xl">
// 			<span style="--value:50;"></span>
// 		</span>
// 		@vctx.Footer()
// 	</div>
// }
